# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d2063640abad6506d49016cafb0199a9283ce35855378103126e33f3b34207fb94b567ab604995c1a6fe03db0a19a2ec3e0383b70eca77e672c700a4d91cf2e

test:
  secret_key_base: b82a06c9a19c201a5912d460dcf4938979cfb86d812bdcd39d800ec8ffb4f97f4c8de4b6007c56b186434b9187a0657b3e74647e770c4688f147363625a20d4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
