# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b8d01c827adb43a961bb602571a65893f66b59c5a36cb1d7e5b31b36c91ea1be914c8d3d082145b58eb809124f593c4605d58220f7798e0d9bdb43889a89c66

test:
  secret_key_base: 5a3b73bc9e66d3e52903d2b4a5d789a430a24b86c6c8a7ae5f21fc5b06a864c97ee3cf9477a29b78e6a02a390e2bce284ac17220ec563f23ba689bb50c93b5e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
